(() => {
  'use strict';

  const STORAGE_KEY = 'sandal_guidance_state_v1';
  const VERSION = '1.0';
  const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
  const currentRoute = () => location.hash.replace(/^#\/?/, '').split('?')[0] || 'dashboard';
  const profileKey = () => {
    const p = window.currentProfile || {};
    return String(p.email || p.id || p.full_name || 'local-user').toLowerCase().replace(/[^a-z0-9@._-]+/gi, '-');
  };
  const defaultState = () => ({ version: VERSION, onboardingCompleted: false, dismissed: [], completedTours: [], preferences: { level: 'standard', contextualTips: true, guidedTours: true }, shown: 0, lastShownAt: 0 });
  const loadAll = () => { try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}'); } catch { return {}; } };
  const saveAll = all => { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(all)); } catch {} };
  const getState = () => { const all = loadAll(); const key = profileKey(); const value = all[key] || defaultState(); if (!value.preferences) value.preferences = defaultState().preferences; all[key] = value; saveAll(all); return value; };
  const updateState = patch => { const all = loadAll(); const key = profileKey(); const next = { ...getState(), ...patch }; all[key] = next; saveAll(all); return next; };
  const pageData = {
    dashboard: { title: 'لوحة التحكم', purpose: 'تعطيك صورة سريعة عن المبيعات والمصروفات والمنتجات والعاملين.', first: 'ابدأ من بطاقة «ابدأ من هنا» واختر التجهيز الذي ينقص مصنعك.', next: 'بعد تجهيز المنتجات والخزائن والعمال، انتقل إلى المبيعات أو التقارير.', rules: ['الأرقام المالية تعتمد على العمليات المعتمدة فقط.', 'راجع التنبيهات والاتصال قبل اتخاذ قرار مالي.'], mistakes: ['اعتبار المسودة حركة مالية نهائية.', 'إهمال ربط الخزنة أو البنك بالعملية.'], after: 'يمكنك فتح القسم المرتبط من البطاقات أو استخدام القائمة الجانبية.' },
    guide: { title: 'دليل التشغيل', purpose: 'يشرح ترتيب تجهيز المصنع وتشغيله من الإعداد إلى التقارير.', first: 'اقرأ التسلسل العام ثم نفذ الخطوات حسب صلاحيات دورك.', next: 'عرّف المنتجات والخزائن والعمال قبل إدخال العمليات اليومية.', rules: ['لا تنتقل إلى الإنتاج قبل تحديد الخام والمخزن.', 'الاعتماد هو الذي يثبت الأثر في المخزون والمال.'], mistakes: ['إدخال العملية في قسم غير مناسب.', 'تجاوز المراجعة قبل الاعتماد.'], after: 'استخدم المساعدة الدائمة من زر «مساعدة» في أي صفحة.' },
    products: { title: 'المنتجات', purpose: 'تعريف المنتجات مرة واحدة لتظهر في البيع والمخزون والإنتاج والمرتجعات.', first: 'اضغط «إضافة منتج» واكتب اسمًا واضحًا ثم الوحدة والتكلفة وسعر البيع.', next: 'راجع الحد الأدنى للمخزون والحقول الإضافية قبل الحفظ.', rules: ['اسم المنتج مطلوب.', 'التكلفة تستخدم لحساب الربح، وسعر البيع يظهر في نقطة البيع.', 'لا يوجد باركود؛ البحث بالاسم أو الرقم الداخلي.'], mistakes: ['ترك التكلفة صفرًا دون قصد.', 'إنشاء منتج مكرر باسم مختلف قليلًا.', 'تعطيل منتج ما زال مطلوبًا في الفواتير.'], after: 'سيظهر المنتج تلقائيًا في النماذج المرتبطة.' },
    inventory: { title: 'المخزون', purpose: 'متابعة الأرصدة والحركات الواردة والصادرة والتحويلات والجرد.', first: 'تأكد من وجود المخازن والمنتجات قبل إنشاء حركة.', next: 'اختر نوع الحركة والمخزن والمنتج والكمية ثم راجعها واعتمدها.', rules: ['الرصيد يعتمد على الحركات المعتمدة.', 'لا تعتمد حركة بكمية سالبة أو دون مخزن صحيح.'], mistakes: ['اختيار مخزن الخام بدل الجاهز.', 'اعتماد حركة مكررة.', 'نسيان سبب التسوية.'], after: 'يتحدث الرصيد والتقارير المرتبطة بعد الاعتماد.' },
    production: { title: 'الإنتاج', purpose: 'تحويل الخام من مخزن المصدر إلى منتج جاهز في مخزن الوجهة مع تتبع الكميات.', first: 'حدد المنتج الناتج ومخزن المصدر والخامة والكمية ومخزن الوجهة.', next: 'راجع الفاقد والمقبول ثم اعتمد أمر الإنتاج.', rules: ['يجب توفر رصيد خام كافٍ.', 'الكمية المقبولة والتالفة والفحص يجب أن تكون منطقية ومترابطة.'], mistakes: ['ترك مخزن المصدر أو الوجهة فارغًا.', 'إدخال كمية إنتاج أكبر من الخام المتاح.', 'نسيان اعتماد أمر الإنتاج.'], after: 'تسجل حركة الخام والمنتج الجاهز ويظهر الأثر في المخزون والتكلفة.' },
    sales: { title: 'المبيعات ونقطة البيع', purpose: 'إنشاء فاتورة بيع مرتبطة بالمنتجات والمخزون والدفع والخزنة أو البنك.', first: 'اضغط «فاتورة بيع»، اختر المنتجات والكميات ثم راجع الإجمالي.', next: 'حدد الدفع؛ عند البنك اكتب البنك ورقم العملية، وعند الكاش اختر الخزنة.', rules: ['لا تعتمد فاتورة دون بند صالح.', 'الدفع البنكي يحتاج بنكًا ورقم عملية.', 'الاعتماد يثبت أثر المخزون والحساب.'], mistakes: ['اختيار طريقة دفع دون حساب مرتبط.', 'إدخال كمية صفرية أو تكرار المنتج في سطرين.', 'طباعة المسودة على أنها فاتورة معتمدة.'], after: 'يمكن طباعة الفاتورة أو إرسالها عبر واتساب بعد الحفظ أو الاعتماد.' },
    returns: { title: 'المرتجعات والتالف', purpose: 'تسجيل المرتجع من خلال رقم الفاتورة وبندها مع فصل الصالح والتالف والفحص.', first: 'ابحث عن الفاتورة واختر البند المراد إرجاعه.', next: 'وزع الكمية على صالح أو تالف أو فحص ثم راجع السبب واعتمد.', rules: ['لا تتجاوز كمية المرتجع الكمية المباعة.', 'التالف والفحص لهما أثر مختلف في المخزون والتكلفة.'], mistakes: ['اختيار فاتورة غير صحيحة.', 'إرجاع كمية أكبر من المتاح.', 'ترك سبب المرتجع غامضًا.'], after: 'يتحدث المخزون والأثر المالي ويظهر السجل في التدقيق.' },
    employees: { title: 'الموظفون', purpose: 'إدارة ملف العامل والقسم والوظيفة والوردية والأجر والحالة.', first: 'أضف العامل باسمه ووظيفته وقسمه ونوع أجره.', next: 'راجع بياناته ثم استخدم الحضور والسلف والحوافز من الأقسام المرتبطة.', rules: ['الاسم والبيانات الأساسية يجب أن تكون واضحة.', 'تعطيل العامل يمنع استخدامه في العمليات الجديدة دون حذف تاريخه.'], mistakes: ['تسجيل العامل مرتين.', 'وضع أجر أو قسم غير صحيح.', 'حذف التاريخ بدل تغيير الحالة.'], after: 'يظهر العامل في الحضور وكشوف المرتبات والبحث.' },
    attendance: { title: 'الحضور والانصراف', purpose: 'تسجيل حركة العامل والوقت والساعات اليومية ثم استخدامها في المرتبات.', first: 'ابحث باسم العامل ثم اضغط زر الحضور أو الانصراف الظاهر له.', next: 'استخدم فلترة اليوم أو الأسبوع أو الشهر لمراجعة الساعات.', rules: ['الحركة تسجل بتاريخ ووقت النظام.', 'التصحيح يكون عبر صلاحية التصحيح وليس بإدخال سجل بديل.'], mistakes: ['تسجيل عامل غير صحيح بسبب تشابه الأسماء.', 'نسيان الانصراف.', 'قراءة سجل يوم واحد على أنه كشف شهري.'], after: 'تظهر الساعات في المراجعة وكشف المرتب حسب قواعد النظام.' },
    suppliers: { title: 'الموردون والمشتريات', purpose: 'تسجيل المورد وشراء المواد أو المنتجات وربط الدفع بالمخزون والقيود.', first: 'أنشئ المورد ثم افتح عملية شراء واختر المخزن والبنود.', next: 'حدد الدفع نقدًا أو بنكًا، راجع الخصم ثم اعتمد العملية.', rules: ['كل بند يحتاج كمية وسعرًا ووحدة مناسبة.', 'الشراء المعتمد يدخل المخزون ويسجل الأثر المالي.'], mistakes: ['اختيار المورد الخطأ.', 'عدم ربط الدفعة بحساب.', 'اعتماد شراء دون مراجعة الخصم والإجمالي.'], after: 'تظهر العملية في المشتريات والمخزون والقيود والتقارير.' },
    treasury: { title: 'الخزائن والبنوك', purpose: 'إدارة الحسابات النقدية والبنكية والتحويلات والجرد.', first: 'راجع الأرصدة الافتتاحية والحسابات النشطة قبل تشغيل المبيعات.', next: 'استخدم الحركة المالية أو التحويل أو الجرد حسب الحاجة.', rules: ['لا تستخدم حسابًا غير نشط.', 'كل حركة مالية يجب أن يكون لها اتجاه ومبلغ وسبب.'], mistakes: ['تسجيل تحويل كأنه مصروف.', 'اختيار خزنة بدل بنك.', 'إهمال التسوية عند اختلاف الرصيد.'], after: 'تتحدث أرصدة الخزائن والبنوك وتظهر في التقارير والقيود.' },
    expenses: { title: 'المصروفات', purpose: 'تسجيل المصروفات حسب القسم والدافع والحساب ثم اعتمادها.', first: 'أنشئ مسودة مصروف مع التصنيف والمبلغ ووصف واضح.', next: 'راجع الحساب وطريقة الدفع ثم اطلب الاعتماد أو اعتمده حسب دورك.', rules: ['المصروف لا يدخل النتيجة إلا بعد الاعتماد.', 'الوصف يساعد سجل التدقيق والمراجعة.'], mistakes: ['إدخال مصروف شخصي كمصروف مصنع.', 'نسيان القسم أو الحساب.', 'اعتماد مبلغ غير مدعوم بوصف.'], after: 'يظهر المصروف في التقارير وقائمة الدخل والقيود بعد الاعتماد.' },
    payroll: { title: 'المرتبات والسلف والحوافز', purpose: 'إعداد كشف المرتب وربط الحضور والسلف والحوافز والدفع.', first: 'تأكد من اكتمال الموظفين والحضور والسلف والحوافز للفترة.', next: 'أنشئ الفترة، راجع كل عامل، ثم اعتمدها بعد المراجعة.', rules: ['السلفة تخصم وفق قواعد الفترة.', 'الحافز يضاف للعامل المحدد أو المجموعة المحددة.', 'اعتماد الفترة خطوة نهائية.'], mistakes: ['إغلاق الفترة قبل إدخال الحافز.', 'اختيار عامل مشابه بالاسم.', 'دفع المرتب دون مراجعة الخصومات.'], after: 'يتولد الأثر المالي وتصبح الفترة قابلة للمراجعة والتدقيق.' },
    journal: { title: 'دفتر اليومية', purpose: 'مراجعة القيود الناتجة عن العمليات حسب الشهر والقسم ومصدر العملية.', first: 'حدد الشهر ومصدر القيد ثم راجع المدين والدائن.', next: 'افتح تفاصيل القيد واطبع القيد عند الحاجة.', rules: ['القيد المتوازن فقط يمر إلى الحالة المرحّلة.', 'لا تعدل قيدًا مرحّلًا خارج مسار التصحيح المعتمد.'], mistakes: ['قراءة قيد مسودة كأنه مرحّل.', 'عدم فحص مصدر القيد.', 'تجاهل فرق المدين والدائن.'], after: 'تستخدم القيود في قائمة الدخل والتدفقات والمركز المالي.' },
    reports: { title: 'التقارير التشغيلية', purpose: 'عرض المبيعات والمشتريات والمخزون والمرتبات والمصروفات مع فلاتر الفترة والمصدر.', first: 'حدد الفترة ومصدر الدفع المطلوب ثم طبّق الفلتر.', next: 'قارن النتائج مع دفتر اليومية أو الجداول التفصيلية قبل اتخاذ القرار.', rules: ['التقارير التشغيلية تعتمد العمليات المعتمدة.', 'الكاش والبنك يمكن فصلهما من الفلتر عند توفره.'], mistakes: ['اختيار فترة خاطئة.', 'خلط المسودات بالمعتمد.', 'اعتبار الإيراد ربحًا قبل خصم التكلفة والمصروفات.'], after: 'يمكن الانتقال إلى القائمة المالية لمراجعة النتيجة المحاسبية.' },
    'financial-statements': { title: 'القوائم المالية', purpose: 'عرض قائمة الدخل والتدفقات النقدية والمركز المالي من القيود المرحّلة.', first: 'حدد الفترة ثم اقرأ القائمة من القيود المرحّلة.', next: 'طابق الإيرادات والتكاليف والمصروفات مع دفتر اليومية.', rules: ['النتيجة المحاسبية لا تعتمد سجلات غير مرحّلة.', 'راجع الأرصدة الافتتاحية والسياسات قبل الاعتماد.'], mistakes: ['خلط الربح الإجمالي بصافي الربح.', 'إهمال تكلفة المبيعات.', 'قراءة فترة غير مكتملة.'], after: 'تستخدم القوائم للمراجعة الإدارية والمحاسبية وليس بدل اعتماد المحاسب.' },
    'bank-reconciliation': { title: 'التسوية البنكية', purpose: 'مطابقة كشف البنك مع الحركات البنكية المسجلة واكتشاف الفروقات.', first: 'أدخل سطر كشف البنك ثم اختر الحركة المطابقة.', next: 'راجع الفروقات غير المطابقة وسجل سببها قبل التسوية.', rules: ['لا تتم المطابقة على حساب بنك غير صحيح.', 'المرجع البنكي يساعد على منع التكرار.'], mistakes: ['مطابقة حركة بتاريخ أو مبلغ مختلف.', 'ترك سطر كشف غير مفسر.', 'تسجيل الفرق كمصروف دون مراجعة.'], after: 'تظهر الحالة في سجل التسوية ويمكن متابعة الفروقات.' },
    audit: { title: 'سجل التدقيق', purpose: 'إظهار من فعل ماذا ومتى وفي أي قسم مع سبب التعديل عند توفره.', first: 'استخدم الفلتر أو البحث للوصول إلى العملية المطلوبة.', next: 'افتح التفاصيل وقارن العملية بالقيد أو السجل المرتبط.', rules: ['السجل تاريخي ولا ينبغي حذفه لتصحيح العرض.', 'لا تظهر كلمات المرور أو مفاتيح الخدمة في التدقيق.'], mistakes: ['الاعتماد على الاسم دون التاريخ.', 'تجاهل سبب التعديل.', 'تعديل البيانات خارج المسار الرسمي.'], after: 'يساعد السجل في المراجعة والتحقيق وتسوية الخلافات.' },
    settings: { title: 'الإعدادات', purpose: 'إدارة هوية المصنع والعملة والضريبة وبيانات الفاتورة وإعادة الضبط الحساسة للمدير.', first: 'حدّث هوية المصنع وبيانات التواصل ثم راجع القيم قبل الحفظ.', next: 'اختبر الفاتورة المطبوعة وتأكد من ظهور الرقم والعنوان والبيانات.', rules: ['الإعدادات متاحة للمدير فقط.', 'لا تضع كلمات مرور أو مفاتيح خدمة في الحقول.', 'إعادة الضبط عملية خطرة وتحتاج عبارة التأكيد.'], mistakes: ['حفظ رقم مصنع ناقص.', 'إدخال بريد غير صحيح.', 'استخدام إعادة الضبط بدل تعديل سجل واحد.'], after: 'تظهر الهوية في الفاتورة ويُحفظ الإعداد مركزيًا.' },
    users: { title: 'المستخدمون', purpose: 'إنشاء وإدارة الحسابات وربطها بالأدوار وتفعيلها أو تعليقها بأمان.', first: 'أنشئ الحساب بالمعلومات الأساسية واربطه بالدور المناسب.', next: 'راجع صلاحيات الدور ثم أرسل بيانات الدخول بطريقة آمنة.', rules: ['لا يمكن عرض كلمة المرور القديمة.', 'تغيير البريد أو كلمة المرور المؤقتة يسجل في التدقيق.', 'الأرشفة تحفظ التاريخ بدل الحذف المحاسبي.'], mistakes: ['منح دور أوسع من مهمة المستخدم.', 'محاولة رؤية كلمة مرور قديمة.', 'تعليق الحساب الخطأ.'], after: 'يظهر المستخدم بحدود دوره وتختفي الأقسام غير المصرح بها.' },
    roles: { title: 'الأدوار والصلاحيات', purpose: 'ضبط ما يستطيع كل دور رؤيته وفعله وحدود المبالغ والحسابات.', first: 'ابدأ بفهم دور المستخدم ونطاق بياناته قبل تعديل أي حد.', next: 'احفظ التغيير ثم اختبره بحساب الدور نفسه.', rules: ['المدير يرى كل الصلاحيات، والمستخدم يرى صلاحيات دوره فقط.', 'تقييد الصلاحية أفضل من الاعتماد على التعليمات وحدها.'], mistakes: ['تفعيل اعتماد دون تفعيل العرض.', 'رفع حد المبلغ دون مراجعة.', 'اختبار الصلاحية بحساب المدير فقط.'], after: 'يُعاد تحميل القائمة حسب الصلاحيات ويُسجل التعديل.' },
    'my-permissions': { title: 'صلاحياتي', purpose: 'عرض الصلاحيات المرتبطة بحسابك فقط، أو كتالوج النظام للمدير.', first: 'راجع دورك الحالي وما يظهر في القائمة الجانبية.', next: 'إذا كانت صلاحية لازمة ناقصة، اطلب من المدير مراجعة الدور.', rules: ['هذه الصفحة لا تمنح صلاحيات؛ هي للعرض والتوضيح.', 'المستخدم لا يرى صلاحيات الأدوار الأخرى.'], mistakes: ['اعتبار ظهور اسم القسم صلاحية تنفيذ.', 'توقع الوصول إلى إعدادات المدير.'], after: 'يمكنك تغيير كلمة مرور حسابك فقط من هذه الصفحة.' }
  };
  const generic = { title: 'هذه الصفحة', purpose: 'تساعدك الصفحة على تنفيذ مهمة مرتبطة بدورك وصلاحياتك.', first: 'اقرأ عنوان الصفحة وحدد الإجراء الأساسي.', next: 'راجع الحقول والتنبيهات قبل الحفظ.', rules: ['نفّذ ما يسمح به دورك فقط.'], mistakes: ['الحفظ دون مراجعة.'], after: 'راجع النتيجة أو سجل التدقيق بعد الإجراء.' };
  const workflows = {
    products: [{ selector: '[data-action="product-new"]', title: 'ابدأ بإضافة منتج', text: 'يفتح نموذج المنتج ويتيح إدخال البيانات الأساسية.' }, { selector: '#product-form [name="name"]', title: 'اكتب اسم المنتج', text: 'استخدم اسمًا واضحًا لا يسبب التباسًا في نقطة البيع.' }, { selector: '#product-form [name="cost_price"]', title: 'أدخل التكلفة', text: 'تستخدم التكلفة لاحقًا في حساب الربح وتقييم المخزون.' }, { selector: '#product-form button.btn-primary', title: 'احفظ بعد المراجعة', text: 'تأكد من الحقول ثم احفظ ليظهر المنتج في الأقسام المرتبطة.' }],
    sales: [{ selector: '[data-action="sale-new"]', title: 'افتح فاتورة جديدة', text: 'ابدأ من زر فاتورة بيع الظاهر حسب صلاحيتك.' }, { selector: '#sale-form [data-sale-product]', title: 'اختر المنتج والكمية', text: 'أضف بندًا صالحًا ولا تكرر المنتج في سطرين.' }, { selector: '#sale-form [name="paid_amount"]', title: 'راجع الدفع', text: 'اختر الكاش أو البنك؛ الدفع البنكي يحتاج البنك ورقم العملية.' }, { selector: '#sale-form button.btn-primary', title: 'احفظ ثم اعتمد', text: 'راجع الإجمالي قبل الحفظ، ثم اعتمد من قائمة المبيعات.' }],
    employees: [{ selector: '[data-action="employee-new"]', title: 'أنشئ ملف العامل', text: 'ابدأ بالاسم والوظيفة والقسم ونوع الأجر.' }, { selector: '#employee-form [name="name"]', title: 'اكتب الاسم بوضوح', text: 'يساعد الاسم الواضح في الحضور والسلف والحوافز.' }, { selector: '#employee-form button.btn-primary', title: 'احفظ الملف', text: 'بعد الحفظ يظهر العامل في الحضور وكشف المرتب.' }],
    attendance: [{ selector: '#attendance-filter', title: 'حدد الفترة', text: 'اختر اليوم أو الأسبوع أو الشهر قبل المراجعة.' }, { selector: '[data-action="attendance-toggle"]', title: 'سجل الحركة', text: 'اضغط زر العامل الصحيح لتسجيل الحضور أو الانصراف بالوقت الحالي.' }],
    payroll: [{ selector: '[data-action="payroll-new"]', title: 'أنشئ فترة المرتب', text: 'ابدأ بعد اكتمال الحضور والسلف والحوافز.' }, { selector: '[data-action="payroll-approve"]', title: 'راجع ثم اعتمد', text: 'الاعتماد يثبت الفترة ويطبق خصم السلف.' }],
    reports: [{ selector: '#reports-filter', title: 'حدد الفترة والمصدر', text: 'استخدم الفلاتر لفصل الكاش والبنك ومقارنة الفترات.' }],
    settings: [{ selector: '#factory-settings-form', title: 'راجع هوية المصنع', text: 'اكتب رقم المصنع والعنوان وبيانات التواصل وعبارة أسفل الفاتورة.' }, { selector: '#factory-settings-form button.btn-primary', title: 'احفظ الإعدادات', text: 'راجع القيم ثم احفظها مركزيًا.' }]
  };

  let inspectMode = false;
  let tour = null;
  let mountTimer = 0;

  function dataFor(route = currentRoute()) { return pageData[route] || generic; }
  function helpShell() {
    if (document.getElementById('gx-help-drawer')) return;
    const drawer = document.createElement('aside');
    drawer.id = 'gx-help-drawer'; drawer.className = 'gx-help-drawer'; drawer.hidden = true;
    drawer.setAttribute('role', 'dialog'); drawer.setAttribute('aria-modal', 'false'); drawer.setAttribute('aria-labelledby', 'gx-help-title');
    drawer.innerHTML = `<div class="gx-help-head"><div><span class="gx-kicker">مركز المساعدة</span><h2 id="gx-help-title">مساعدك داخل النظام</h2></div><button class="gx-icon-btn" data-gx-action="close" aria-label="إغلاق المساعدة">×</button></div><div class="gx-help-body"><div class="gx-context-line"><span id="gx-context-title"></span><span id="gx-online-state"></span></div><label class="gx-search-label" for="gx-help-search">ما الذي تحتاج مساعدة فيه؟</label><input id="gx-help-search" class="gx-help-search" type="search" placeholder="ابحث في الصفحات والخطوات والأخطاء" autocomplete="off"><div id="gx-help-results" class="gx-help-results"></div><div id="gx-help-actions" class="gx-help-actions"><button class="btn btn-primary" data-gx-action="page-guide">كيف أستخدم هذه الصفحة؟</button><button class="btn btn-soft" data-gx-action="tour">أرني كيف</button><button class="btn btn-soft" data-gx-action="workflow">طريقة العمل الصحيحة</button><button class="btn btn-outline" data-gx-action="inspect">ما هذا؟</button></div><div id="gx-help-content" class="gx-help-content"></div></div><div class="gx-help-foot"><button class="gx-text-btn" data-gx-action="preferences">تفضيلات الإرشاد</button><button class="gx-text-btn" data-gx-action="reset">إعادة النصائح</button></div></aside>`;
    document.body.append(drawer);
    document.getElementById('gx-help-search').addEventListener('input', renderSearch);
  }
  function addEntryPoints() {
    if (!window.currentProfile) { document.querySelectorAll('.gx-help-fab,.gx-help-entry,#gx-help-drawer,#gx-onboarding,#gx-info-popover,#gx-tour-layer').forEach(el => el.remove()); document.body.classList.remove('gx-help-open','gx-inspect-mode'); inspectMode = false; tour = null; return; }
    helpShell();
    if (!document.querySelector('.gx-help-entry')) {
      const profileBox = document.querySelector('.profile-box');
      const button = document.createElement('button'); button.className = 'btn btn-outline btn-sm gx-help-entry'; button.type = 'button'; button.dataset.gxAction = 'open'; button.setAttribute('aria-label', 'فتح مركز المساعدة'); button.innerHTML = '<span aria-hidden="true">?</span><span>مساعدة</span>';
      if (profileBox) profileBox.insertBefore(button, profileBox.lastElementChild || null); else document.body.append(button);
    }
    if (!document.querySelector('.gx-help-fab')) {
      const fab = document.createElement('button'); fab.className = 'gx-help-fab'; fab.type = 'button'; fab.dataset.gxAction = 'open'; fab.setAttribute('aria-label', 'فتح المساعدة'); fab.innerHTML = '<strong>?</strong><span>مساعدة</span>'; document.body.append(fab);
    }
    const state = getState();
    const title = document.getElementById('gx-context-title'); if (title) title.textContent = `${dataFor().title} · ${window.currentProfile?.role_name || 'المستخدم'}`;
    const onlineState = document.getElementById('gx-online-state'); if (onlineState) { onlineState.textContent = navigator.onLine === false ? 'أوفلاين · الإرشاد متاح' : 'متصل'; onlineState.className = navigator.onLine === false ? 'gx-offline' : 'gx-online'; }
    if (!state.onboardingCompleted && state.preferences.contextualTips && !document.getElementById('gx-onboarding')) showOnboarding();
  }
  function showOnboarding() {
    const box = document.createElement('section'); box.id = 'gx-onboarding'; box.className = 'gx-onboarding'; box.setAttribute('role', 'status');
    box.innerHTML = `<div class="gx-onboarding-mark">SP</div><div class="gx-onboarding-copy"><span class="gx-kicker">بداية سريعة</span><h2>مرحبًا بك. الإرشاد متاح أثناء العمل.</h2><p>لن نمنعك من استخدام النظام. افتح المساعدة وقتما تريد، واستخدم «كيف أستخدم هذه الصفحة؟» أو «أرني كيف» للخطوة المناسبة.</p><div class="gx-onboarding-points"><span>✓ شرح الصفحة الحالية</span><span>✓ منع أخطاء الحقول</span><span>✓ جولات قابلة للتخطي</span></div></div><div class="gx-onboarding-actions"><button class="btn btn-primary btn-sm" data-gx-action="onboarding-start">ابدأ الجولة القصيرة</button><button class="gx-text-btn" data-gx-action="onboarding-dismiss">تخطي الآن</button></div>`;
    document.body.append(box);
  }
  function closeOnboarding(done = true) { document.getElementById('gx-onboarding')?.remove(); if (done) updateState({ onboardingCompleted: true }); }
  function openDrawer(mode = 'home') { helpShell(); const drawer = document.getElementById('gx-help-drawer'); drawer.hidden = false; document.body.classList.add('gx-help-open'); renderMode(mode); setTimeout(() => document.getElementById('gx-help-search')?.focus(), 30); }
  function closeDrawer() { const drawer = document.getElementById('gx-help-drawer'); if (drawer) drawer.hidden = true; document.body.classList.remove('gx-help-open'); }
  function renderMode(mode) {
    const content = document.getElementById('gx-help-content'); if (!content) return;
    const d = dataFor();
    if (mode === 'page-guide') content.innerHTML = guideHtml(d);
    else if (mode === 'workflow') content.innerHTML = workflowHtml(d);
    else if (mode === 'preferences') content.innerHTML = preferencesHtml();
    else content.innerHTML = homeHtml(d);
    const actions = document.getElementById('gx-help-actions'); if (actions) actions.hidden = mode === 'preferences';
    const level = document.querySelector('[name="gx-level"]'); if (level) level.value = getState().preferences.level;
    const tips = document.querySelector('[name="gx-contextual"]'); if (tips) tips.checked = !!getState().preferences.contextualTips;
    const tours = document.querySelector('[name="gx-tours"]'); if (tours) tours.checked = !!getState().preferences.guidedTours;
  }
  function homeHtml(d) { return `<div class="gx-help-welcome"><span class="gx-kicker">مساعدة مرتبطة بالصفحة</span><h3>${esc(d.title)}</h3><p>${esc(d.purpose)}</p><div class="gx-next-card"><strong>الخطوة المقترحة الآن</strong><span>${esc(d.first)}</span></div><p class="gx-muted">يمكنك إغلاق هذه اللوحة ومواصلة العمل؛ المساعدة لا تغطي النماذج ولا توقف المسار.</p></div><div class="gx-help-links"><button data-gx-action="mistakes">الأخطاء الشائعة هنا</button><button data-gx-action="what-next">ماذا بعد الحفظ؟</button><button data-gx-action="offline">المساعدة أثناء الأوفلاين</button></div>`; }
  function guideHtml(d) { return `<div class="gx-guide-block"><span class="gx-kicker">دليل الصفحة</span><h3>${esc(d.title)}</h3><div class="gx-guide-item"><b>ما وظيفة الصفحة؟</b><p>${esc(d.purpose)}</p></div><div class="gx-guide-item"><b>ماذا أفعل أولًا؟</b><p>${esc(d.first)}</p></div><div class="gx-guide-item"><b>ما الخطوة التالية؟</b><p>${esc(d.next)}</p></div><div class="gx-guide-item"><b>قواعد مهمة</b><ul>${d.rules.map(x => `<li>${esc(x)}</li>`).join('')}</ul></div><div class="gx-guide-item gx-warning"><b>أخطاء شائعة وكيف تتجنبها</b><ul>${d.mistakes.map(x => `<li>${esc(x)}</li>`).join('')}</ul></div><div class="gx-guide-item"><b>ماذا يحدث بعد الإكمال؟</b><p>${esc(d.after)}</p></div></div>`; }
  function workflowHtml(d) { const steps = workflows[currentRoute()] || [{ selector: '.page-header', title: 'افهم المهمة الحالية', text: d.first }, { selector: '.panel', title: 'أدخل البيانات ثم راجعها', text: d.next }]; return `<div class="gx-guide-block"><span class="gx-kicker">طريقة العمل الصحيحة</span><h3>${esc(d.title)}</h3><p>${esc(d.purpose)}</p><ol class="gx-workflow-list">${steps.map((s, i) => `<li><span>${i + 1}</span><div><b>${esc(s.title)}</b><p>${esc(s.text)}</p></div></li>`).join('')}</ol><button class="btn btn-primary btn-wide" data-gx-action="tour">ابدأ جولة على عناصر الصفحة</button></div>`; }
  function preferencesHtml() { const p = getState().preferences; return `<div class="gx-guide-block"><span class="gx-kicker">تحكمك أولًا</span><h3>تفضيلات الإرشاد</h3><p>يمكنك تقليل الإرشاد التلقائي دون فقدان زر المساعدة اليدوي.</p><label class="gx-setting-row"><span>مستوى الإرشاد التلقائي<select name="gx-level"><option value="minimal">مختصر</option><option value="standard">قياسي</option><option value="detailed">مفصل</option></select></span></label><label class="gx-setting-check"><input name="gx-contextual" type="checkbox" ${p.contextualTips ? 'checked' : ''}> إظهار التلميحات السياقية</label><label class="gx-setting-check"><input name="gx-tours" type="checkbox" ${p.guidedTours ? 'checked' : ''}> السماح بالجولات عند طلبها</label><button class="btn btn-primary btn-wide" data-gx-action="save-preferences">حفظ التفضيلات</button><p class="gx-muted">يبقى مركز المساعدة متاحًا حتى عند اختيار المستوى المختصر أو إيقاف التلميحات.</p></div>`; }
  function renderSearch() { const input = document.getElementById('gx-help-search'); const results = document.getElementById('gx-help-results'); if (!input || !results) return; const q = input.value.trim().toLowerCase(); if (!q) { results.hidden = true; results.innerHTML = ''; return; } const items = Object.entries(pageData).flatMap(([route, d]) => [ { title: d.title, text: d.purpose, mode: 'page-guide', route }, { title: `طريقة العمل: ${d.title}`, text: d.first, mode: 'workflow', route }, ...d.mistakes.map(text => ({ title: `خطأ شائع: ${d.title}`, text, mode: 'page-guide', route })) ]).filter(x => `${x.title} ${x.text}`.toLowerCase().includes(q)).slice(0, 10); results.hidden = false; results.innerHTML = items.length ? items.map(x => `<button data-gx-search-route="${esc(x.route)}" data-gx-search-mode="${esc(x.mode)}"><b>${esc(x.title)}</b><span>${esc(x.text)}</span></button>`).join('') : '<div class="gx-no-results">لم نجد نتيجة مطابقة. جرّب اسم القسم أو كلمة «دفع» أو «اعتماد».</div>'; }
  function annotateInfo() {
    const actionNames = { 'product-new':'إضافة منتج جديد', 'sale-new':'إنشاء فاتورة بيع', 'purchase-new':'إنشاء عملية شراء', 'employee-new':'إضافة عامل', 'attendance-toggle':'تسجيل حضور أو انصراف العامل', 'payroll-new':'إنشاء فترة مرتبات', 'payroll-approve':'اعتماد فترة المرتبات', 'journal-print':'طباعة القيد', 'sale-print':'طباعة الفاتورة', 'sale-payment':'تسجيل دفعة لاحقة', 'settings':'فتح إعدادات المصنع', 'go-guide':'فتح دليل التشغيل' };
    document.querySelectorAll('[data-action]').forEach(el => { if (!el.dataset.gxInfo && actionNames[el.dataset.action]) el.dataset.gxInfo = actionNames[el.dataset.action]; });
    document.querySelectorAll('input,select,textarea').forEach(el => { if (el.dataset.gxInfo) return; const field = el.closest('.field'); const label = field?.textContent?.replace(/\s+/g, ' ').trim().slice(0, 100); if (label) el.dataset.gxInfo = `هذا الحقل خاص بـ ${label}`; });
  }
  function addEmptyHelp() { document.querySelectorAll('.empty-state').forEach(el => { if (el.querySelector('[data-gx-action="page-guide"]')) return; const button = document.createElement('button'); button.type = 'button'; button.className = 'gx-empty-help'; button.dataset.gxAction = 'page-guide'; button.textContent = 'كيف أبدأ؟'; el.append(button); }); }
  function showInfo(el) { const old = document.getElementById('gx-info-popover'); old?.remove(); const pop = document.createElement('div'); pop.id = 'gx-info-popover'; pop.className = 'gx-info-popover'; pop.setAttribute('role', 'status'); pop.innerHTML = `<strong>${esc(el.tagName === 'INPUT' || el.tagName === 'SELECT' || el.tagName === 'TEXTAREA' ? 'معلومة عن الحقل' : 'معلومة عن العنصر')}</strong><span>${esc(el.dataset.gxInfo || 'هذا العنصر يساعدك على إكمال المهمة الحالية.')}</span><button class="gx-text-btn" data-gx-action="close-info">فهمت</button>`; document.body.append(pop); const r = el.getBoundingClientRect(); pop.style.top = `${Math.min(window.innerHeight - 150, Math.max(12, r.bottom + 8))}px`; pop.style.left = `${Math.min(window.innerWidth - 320, Math.max(12, r.left))}px`; }
  function startTour() {
    const state = getState(); if (state.preferences.guidedTours === false) { toastSafe('الجولات متوقفة من التفضيلات؛ يمكنك تفعيلها من إعدادات الإرشاد.', 'error'); return; }
    const d = dataFor(); const raw = workflows[currentRoute()] || [{ selector: '.page-header', title: 'ابدأ بفهم الصفحة', text: d.purpose }, { selector: '.panel', title: 'نفذ الخطوة الأساسية', text: d.first }]; const steps = raw.filter(s => document.querySelector(s.selector));
    if (!steps.length) { openDrawer('page-guide'); toastSafe('لا توجد عناصر ظاهرة الآن للجولة؛ افتح النموذج أو أضف سجلًا أولًا.', 'error'); return; }
    closeDrawer(); document.getElementById('gx-onboarding')?.remove(); tour = { steps, index: 0 }; renderTour();
  }
  function renderTour() {
    if (!tour) return; let layer = document.getElementById('gx-tour-layer'); if (!layer) { layer = document.createElement('div'); layer.id = 'gx-tour-layer'; layer.className = 'gx-tour-layer'; document.body.append(layer); }
    const step = tour.steps[tour.index]; const target = document.querySelector(step.selector); if (!target) { if (tour.index < tour.steps.length - 1) { tour.index++; renderTour(); return; } return finishTour(false); }
    const r = target.getBoundingClientRect(); const top = Math.max(10, Math.min(window.innerHeight - 200, r.bottom + 12)); const left = Math.max(10, Math.min(window.innerWidth - 370, r.left)); layer.innerHTML = `<div class="gx-tour-shade"></div><div class="gx-tour-focus" style="top:${Math.max(6, r.top - 6)}px;left:${Math.max(6, r.left - 6)}px;width:${Math.max(20, r.width + 12)}px;height:${Math.max(20, r.height + 12)}px"></div><section class="gx-tour-card" style="top:${top}px;left:${left}px" role="dialog" aria-live="polite" tabindex="-1"><span class="gx-kicker">جولة الإرشاد · ${tour.index + 1}/${tour.steps.length}</span><h3>${esc(step.title)}</h3><p>${esc(step.text)}</p><div class="gx-tour-actions"><button class="btn btn-soft btn-sm" data-gx-action="tour-prev" ${tour.index === 0 ? 'disabled' : ''}>السابق</button><button class="btn btn-primary btn-sm" data-gx-action="tour-next">${tour.index === tour.steps.length - 1 ? 'إنهاء' : 'التالي'}</button><button class="gx-text-btn" data-gx-action="tour-exit">تخطي</button></div></section>`;
    target.scrollIntoView({ block: 'nearest', inline: 'nearest' }); requestAnimationFrame(() => document.querySelector('.gx-tour-card')?.focus());
  }
  function finishTour(completed = true) { if (completed) { const state = getState(); updateState({ completedTours: [...new Set([...(state.completedTours || []), currentRoute()])] }); toastSafe('انتهت الجولة. يمكنك إعادة تشغيلها من زر المساعدة في أي وقت.'); } document.getElementById('gx-tour-layer')?.remove(); tour = null; }
  function toastSafe(text, type = 'ok') { const region = document.getElementById('toast-region'); if (!region) return; const el = document.createElement('div'); el.className = `toast ${type === 'error' ? 'error' : ''}`; el.textContent = text; region.append(el); setTimeout(() => el.remove(), 4200); }
  function validateForm(e) { const form = e.target; if (!(form instanceof HTMLFormElement) || form.id === 'login-form') return; if (!form.checkValidity()) { e.preventDefault(); e.stopImmediatePropagation(); const invalid = form.querySelector(':invalid'); invalid?.focus(); const label = invalid?.closest('.field')?.textContent?.replace(/\s+/g, ' ').trim().replace(/[*:]+$/g, '') || 'الحقل المحدد'; let msg = `أكمل حقل «${label}» قبل المتابعة.`; if (invalid?.type === 'email') msg = `اكتب بريدًا إلكترونيًا صحيحًا في حقل «${label}».`; else if (invalid?.type === 'number' && invalid.validity.rangeUnderflow) msg = `يجب أن تكون قيمة «${label}» مساوية أو أكبر من ${invalid.min}.`; else if (invalid?.validity.tooShort) msg = `يجب أن يحتوي «${label}» على ${invalid.minLength} أحرف على الأقل.`; toastSafe(`راجع الحقول: ${msg}`, 'error'); invalid?.classList.add('gx-invalid'); setTimeout(() => invalid?.classList.remove('gx-invalid'), 2200); } }
  function handleAction(action, el) {
    if (action === 'open') return openDrawer();
    if (action === 'close') return closeDrawer();
    if (action === 'page-guide') return openDrawer('page-guide');
    if (action === 'workflow') return openDrawer('workflow');
    if (action === 'tour' || action === 'onboarding-start') { if (action === 'onboarding-start') closeOnboarding(); return startTour(); }
    if (action === 'inspect') { inspectMode = !inspectMode; document.body.classList.toggle('gx-inspect-mode', inspectMode); toastSafe(inspectMode ? 'وضع «ما هذا؟» مفعل. اضغط عنصرًا مدعومًا لمعرفة وظيفته.' : 'تم إيقاف وضع «ما هذا؟».'); return; }
    if (action === 'close-info') return document.getElementById('gx-info-popover')?.remove();
    if (action === 'onboarding-dismiss') return closeOnboarding();
    if (action === 'tour-next') { if (!tour) return; if (tour.index >= tour.steps.length - 1) return finishTour(true); tour.index++; return renderTour(); }
    if (action === 'tour-prev') { if (!tour) return; tour.index = Math.max(0, tour.index - 1); return renderTour(); }
    if (action === 'tour-exit') return finishTour(false);
    if (action === 'preferences') return renderMode('preferences');
    if (action === 'save-preferences') { const level = document.querySelector('[name="gx-level"]')?.value || 'standard'; const contextualTips = !!document.querySelector('[name="gx-contextual"]')?.checked; const guidedTours = !!document.querySelector('[name="gx-tours"]')?.checked; const s = getState(); updateState({ preferences: { ...s.preferences, level, contextualTips, guidedTours } }); toastSafe('تم حفظ تفضيلات الإرشاد. المساعدة اليدوية ستظل متاحة.'); return renderMode('home'); }
    if (action === 'reset') { updateState({ dismissed: [], onboardingCompleted: false, completedTours: [], shown: 0 }); closeDrawer(); document.getElementById('gx-onboarding')?.remove(); toastSafe('تمت إعادة النصائح والجولات لهذا المستخدم.'); return; }
    if (action === 'mistakes') { const d = dataFor(); const content = document.getElementById('gx-help-content'); if (content) content.innerHTML = `<div class="gx-guide-block"><span class="gx-kicker">تجنب الأخطاء</span><h3>أخطاء شائعة في ${esc(d.title)}</h3><ul>${d.mistakes.map(x => `<li>${esc(x)}</li>`).join('')}</ul><p class="gx-muted">إذا حدث خطأ، لا تعيد الإدخال عشوائيًا. راجع الرسالة، صحح الحقل، ثم تحقق من سجل التدقيق.</p></div>`; return; }
    if (action === 'what-next') { const d = dataFor(); const content = document.getElementById('gx-help-content'); if (content) content.innerHTML = `<div class="gx-guide-block"><span class="gx-kicker">بعد الإكمال</span><h3>الخطوة التالية</h3><p>${esc(d.after)}</p><p class="gx-muted">استخدم القائمة أو زر «مساعدة» للعودة إلى الشرح متى احتجت.</p></div>`; return; }
    if (action === 'offline') { const content = document.getElementById('gx-help-content'); if (content) content.innerHTML = `<div class="gx-guide-block"><span class="gx-kicker">الأوفلاين</span><h3>ماذا يحدث عند انقطاع الاتصال؟</h3><p>يبقى الإرشاد والصفحة الحالية متاحين. ستظهر حالة «أوفلاين»، والعمليات التي لا يمكن تنفيذها محليًا تنتظر عودة الشبكة بدل إخفاء النتيجة.</p><p class="gx-muted">لا تعتبر العملية مكتملة إلا بعد ظهور رسالة النجاح أو مزامنتها عند عودة الاتصال.</p></div>`; return; }
  }
  document.addEventListener('click', e => {
    const gx = e.target.closest('[data-gx-action]');
    if (gx) { e.preventDefault(); e.stopPropagation(); handleAction(gx.dataset.gxAction, gx); return; }
    const searchResult = e.target.closest('[data-gx-search-route]');
    if (searchResult) { e.preventDefault(); location.hash = `#/${searchResult.dataset.gxSearchRoute}`; setTimeout(() => openDrawer(searchResult.dataset.gxSearchMode || 'page-guide'), 160); return; }
    if (inspectMode && !e.target.closest('#gx-help-drawer') && !e.target.closest('#gx-info-popover')) { const target = e.target.closest('[data-gx-info]'); if (target) { e.preventDefault(); e.stopImmediatePropagation(); showInfo(target); } }
  }, true);
  document.addEventListener('submit', validateForm, true);
  document.addEventListener('keydown', e => { if (e.key === '?' && !['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)) { e.preventDefault(); openDrawer(); return; } if (e.key === 'Escape') { if (tour) finishTour(false); else if (inspectMode) { inspectMode = false; document.body.classList.remove('gx-inspect-mode'); } else closeDrawer(); } });
  window.addEventListener('resize', () => { if (tour) renderTour(); });
  window.addEventListener('scroll', () => { if (tour) renderTour(); }, true);
  window.addEventListener('online', () => { const el = document.getElementById('gx-online-state'); if (el) { el.textContent = 'متصل'; el.className = 'gx-online'; } });
  window.addEventListener('offline', () => { const el = document.getElementById('gx-online-state'); if (el) { el.textContent = 'أوفلاين · الإرشاد متاح'; el.className = 'gx-offline'; } });
  window.addEventListener('hashchange', () => setTimeout(() => { addEntryPoints(); annotateInfo(); addEmptyHelp(); }, 80));
  const observer = new MutationObserver(() => { clearTimeout(mountTimer); mountTimer = setTimeout(() => { addEntryPoints(); annotateInfo(); addEmptyHelp(); }, 40); });
  observer.observe(document.getElementById('app') || document.body, { childList: true, subtree: true });
  setTimeout(() => { addEntryPoints(); annotateInfo(); addEmptyHelp(); }, 180);
  window.GuidanceEngine = { open: openDrawer, startTour, pageGuide: () => openDrawer('page-guide'), setInspect: value => { inspectMode = !!value; document.body.classList.toggle('gx-inspect-mode', inspectMode); } };
})();
