const cfg=window.APP_CONFIG||{};
const supabaseReady=Boolean(cfg.supabaseUrl&&cfg.supabaseAnonKey&&window.supabase);
const db=supabaseReady?window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}}):null;
const queueKey=cfg.offlineQueueKey||'sandal_factory_offline_queue_v1';
const cacheKey=cfg.offlineCacheKey||'sandal_factory_read_cache_v1';
let flushInFlight=null;
function readQueue(){try{const value=JSON.parse(localStorage.getItem(queueKey)||'[]');return Array.isArray(value)?value:[]}catch{return[]}}
function writeQueue(items){try{localStorage.setItem(queueKey,JSON.stringify(items))}catch{}}
async function readCache(){if(window.offlineStore){const rows=await window.offlineStore.list();return Object.fromEntries(rows.filter(row=>row.id.startsWith('cache:')).map(row=>[row.id.slice(6),row.value]))}try{const value=JSON.parse(localStorage.getItem(cacheKey)||'{}');return value&&typeof value==='object'?value:{}}catch{return{}}}
async function writeCache(key,data){if(window.offlineStore){await window.offlineStore.put(`cache:${key}`,{saved_at:new Date().toISOString(),data});const rows=(await window.offlineStore.list()).filter(row=>row.id.startsWith('cache:')).sort((a,b)=>String(b.value?.saved_at||'').localeCompare(String(a.value?.saved_at||'')));for(const row of rows.slice(30))await window.offlineStore.remove(row.id);return}try{const cache=JSON.parse(localStorage.getItem(cacheKey)||'{}');cache[key]={saved_at:new Date().toISOString(),data};const keep=Object.entries(cache).sort((a,b)=>String(b[1]?.saved_at||'').localeCompare(String(a[1]?.saved_at||''))).slice(0,30);localStorage.setItem(cacheKey,JSON.stringify(Object.fromEntries(keep)))}catch{}}
function cacheId(table,columns,options){try{return`${table}|${columns}|${JSON.stringify(options||{})}`}catch{return`${table}|${columns}`}}
function makeId(){return crypto?.randomUUID?crypto.randomUUID():`local-${Date.now()}-${Math.random().toString(16).slice(2)}`}
function online(){return navigator.onLine!==false}
const offlineMigration=window.offlineStore?.migrateLegacyCache(cacheKey).catch(()=>null);async function dbSelect(table,columns='*',options={}){if(!db)throw new Error('لم يتم إعداد اتصال Supabase.');await offlineMigration;const id=cacheId(table,columns,options),cache=await readCache(),cached=cache[id]?.data;if(!online()){if(cached)return cached;throw new Error('لا توجد نسخة محفوظة لهذه الصفحة أثناء انقطاع الاتصال.')}let q=db.from(table).select(columns);if(options.order)q=q.order(options.order.column,{ascending:options.order.ascending!==false});if(options.limit)q=q.limit(options.limit);if(options.eq)Object.entries(options.eq).forEach(([k,v])=>{q=q.eq(k,v)});if(options.neq)Object.entries(options.neq).forEach(([k,v])=>{q=q.neq(k,v)});if(options.gte)q=q.gte(options.gte[0],options.gte[1]);if(options.lte)q=q.lte(options.lte[0],options.lte[1]);if(options.ilike)q=q.ilike(options.ilike[0],options.ilike[1]);try{const{data,error}=await q;if(error)throw error;const result=data||[];await writeCache(id,result);return result}catch(error){if(cached)return cached;throw error}}
async function dbInsert(table,payload,opts={}){if(!db)throw new Error('لم يتم إعداد اتصال Supabase.');if(!online()&&opts.queue){const item={id:makeId(),kind:'insert',table,payload,created_at:new Date().toISOString(),status:'queued'};const q=readQueue();q.push(item);writeQueue(q);window.dispatchEvent(new CustomEvent('queue:updated',{detail:{queued:1,remaining:q.length}}));return{...payload,__queued:item.id}}if(!online())throw new Error('لا يوجد اتصال؛ هذه العملية لا تسمح بالحفظ المؤجل.');const{data,error}=await db.from(table).insert(payload).select().single();if(error)throw error;return data}
async function dbUpdate(table,values,filters){if(!db)throw new Error('لم يتم إعداد اتصال Supabase.');if(!online())throw new Error('لا يوجد اتصال؛ لا يمكن تعديل السجل بأمان الآن.');let q=db.from(table).update(values);Object.entries(filters||{}).forEach(([k,v])=>{q=q.eq(k,v)});const{data,error}=await q.select().single();if(error)throw error;return data}
async function dbRpc(name,args={}){if(!db)throw new Error('لم يتم إعداد اتصال Supabase.');if(!online())throw new Error('هذه العملية تحتاج اتصالًا بالإنترنت للتأكد من الرصيد ومنع التكرار.');const{data,error}=await db.rpc(name,args);if(error)throw error;return data}
async function dbFunction(name,payload={}){if(!db)throw new Error('لم يتم إعداد اتصال Supabase.');if(!online())throw new Error('هذه العملية تحتاج اتصالًا بالإنترنت.');const{data,error}=await db.functions.invoke(name,{body:payload});if(error)throw error;return data}
const stableValue=value=>{if(Array.isArray(value))return value.map(stableValue);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(key=>[key,stableValue(value[key])]));return value};async function requestHash(value){const raw=new TextEncoder().encode(JSON.stringify(stableValue(value)));const digest=await crypto.subtle.digest('SHA-256',raw);return [...new Uint8Array(digest)].map(byte=>byte.toString(16).padStart(2,'0')).join('')}
async function idempotentRpc(name,args={},options={}){if(!db)throw new Error('لم يتم إعداد اتصال Supabase.');const idempotencyKey=options.idempotencyKey||makeId(),request_hash=await requestHash({name,args});if(!online()){if(options.queue&&window.offlineStore){const record=await window.offlineStore.enqueue({idempotency_key:idempotencyKey,operation_name:name,request_hash,payload:{name,args},status:'pending'});window.dispatchEvent(new CustomEvent('queue:updated',{detail:{queued:1}}));return{queued:true,idempotency_key:idempotencyKey,record}}throw new Error('هذه العملية تحتاج اتصالًا بالإنترنت.')}const{data:claim,error:claimError}=await db.rpc('claim_idempotency_key',{p_idempotency_key:idempotencyKey,p_operation_name:name,p_request_hash:request_hash});if(claimError)throw claimError;if(!claim?.claimed){if(claim.status==='conflict')throw new Error('تعارض في إعادة استخدام معرف العملية.');if(claim.status==='failed')throw new Error(claim.response_payload?.error||'فشلت العملية السابقة بهذا المعرف.');if(claim.status==='claimed')throw new Error('العملية بهذا المعرف قيد التنفيذ على الخادم.');return claim.response_payload}try{const{data,error}=await db.rpc(name,{...args,p_idempotency_key:idempotencyKey,p_request_hash:request_hash});if(error)throw error;await db.rpc('complete_idempotency_key',{p_idempotency_key:idempotencyKey,p_status:'succeeded',p_response_payload:data});return data}catch(error){await db.rpc('complete_idempotency_key',{p_idempotency_key:idempotencyKey,p_status:'failed',p_response_payload:{error:String(error.message||error)}}).catch(()=>{});throw error}}
async function flushQueue(){if(flushInFlight)return flushInFlight;if(!db||!online())return{sent:0,remaining:readQueue().length};flushInFlight=(async()=>{const q=readQueue(),remaining=[];for(const item of q){try{if(item.kind==='insert'){const{error}=await db.from(item.table).insert(item.payload);if(error)throw error}}catch(error){remaining.push({...item,error:String(error.message||error)})}}writeQueue(remaining);return{sent:q.length-remaining.length,remaining:remaining.length}})();try{return await flushInFlight}finally{flushInFlight=null}}
async function flushOfflineOutbox(){if(!db||!online()||!window.offlineStore)return{sent:0,remaining:0,conflicts:0};const items=await window.offlineStore.getOutbox(),pending=items.filter(item=>['pending','failed_retryable'].includes(item.status));let sent=0,remaining=0,conflicts=0;for(const item of pending){await window.offlineStore.updateOutbox(item.idempotency_key,{status:'sending',error:null});try{const payload=item.payload||{};const data=await idempotentRpc(payload.name,payload.args,{idempotencyKey:item.idempotency_key});await window.offlineStore.updateOutbox(item.idempotency_key,{status:'succeeded',server_result:data});await window.offlineStore.saveReceipt({idempotency_key:item.idempotency_key,operation_name:item.operation_name,status:'succeeded',server_result:data,completed_at:new Date().toISOString()});sent+=1}catch(error){const message=String(error.message||error),isConflict=/conflict|تعارض|invalid|غير صالح|permission|policy|not authorized|رصيد|stock|quantity/i.test(message),status=isConflict?'conflict':'failed_retryable';await window.offlineStore.updateOutbox(item.idempotency_key,{status,error:message,attempts:Number(item.attempts||0)+1});if(isConflict)conflicts+=1;else remaining+=1}}return{sent,remaining,conflicts}}
function queuedCount(){return readQueue().length}
function friendlyError(error){const m=String(error?.message||error||'حدث خطأ غير معروف');if(/offline|غير متصل|اتصال بالإنترنت|نسخة محفوظة/i.test(m))return'لا يوجد اتصال حاليًا؛ عادت الواجهة للبيانات المحفوظة أو انتظر عودة الشبكة.';if(/JWT|auth|password|credential/i.test(m))return'بيانات الدخول غير صحيحة أو انتهت الجلسة.';if(/permission|policy|denied|RLS|not authorized/i.test(m))return'ليست لديك صلاحية لتنفيذ هذه العملية.';if(/duplicate|unique/i.test(m))return'هذا الرقم مستخدم من قبل.';if(/stock|quantity|balance|رصيد/i.test(m))return'الكمية أو الرصيد المتاح لا يكفي لتنفيذ العملية.';return m}
window.addEventListener('online',()=>{Promise.all([flushQueue(),flushOfflineOutbox()]).then(results=>{const result={sent:results.reduce((n,x)=>n+Number(x.sent||0),0),remaining:results.reduce((n,x)=>n+Number(x.remaining||0),0),conflicts:results.reduce((n,x)=>n+Number(x.conflicts||0),0)};window.dispatchEvent(new CustomEvent('queue:updated',{detail:result}));window.dispatchEvent(new CustomEvent('connection:restored',{detail:result}))}).catch(error=>window.dispatchEvent(new CustomEvent('connection:restored',{detail:{remaining:queuedCount(),error:String(error.message||error)}})))});
window.addEventListener('offline',()=>window.dispatchEvent(new CustomEvent('connection:lost')));
