-- إزالة سياسات الوصول المفتوحة التي أُنشئت في الترحيل الأساسي
DO $$ DECLARE t text; BEGIN FOR t IN SELECT unnest(ARRAY['activity_logs','attendance_records','bank_transactions','banks','cash_registers','cash_transactions','customers','damaged_goods','departments','employee_advances','employee_incentives','employees','expenses','job_titles','payroll_periods','payroll_records','permissions','product_categories','production_materials','production_orders','products','profiles','purchase_items','purchases','raw_materials','return_items','returns','role_permissions','roles','sale_items','sale_payments','sales','settings','shifts','stock_movement_lines','stock_movements','supplier_payments','suppliers','units','user_roles','warehouses','finance_transfers','cash_counts']) LOOP EXECUTE format('drop policy if exists %I on public.%I',t||'_access',t); END LOOP; END $$;

create policy activity_logs_view on public.activity_logs for select using (current_user_has_permission('audit.view') or current_user_is_manager());
create policy attendance_view on public.attendance_records for select using (current_user_has_permission('attendance.view') or current_user_is_manager());
create policy attendance_write on public.attendance_records for insert with check (current_user_has_permission('attendance.create') and created_by=auth.uid());
create policy finance_cash_view on public.cash_registers for select using (current_user_has_permission('treasury.view') or current_user_is_manager());
create policy finance_bank_view on public.banks for select using (current_user_has_permission('treasury.view') or current_user_is_manager());
create policy finance_cash_tx_view on public.cash_transactions for select using (current_user_has_permission('treasury.view') or current_user_is_manager());
create policy finance_bank_tx_view on public.bank_transactions for select using (current_user_has_permission('treasury.view') or current_user_is_manager());
create policy finance_expenses_view on public.expenses for select using (current_user_has_permission('expenses.view') or current_user_is_manager());
create policy finance_payments_view on public.supplier_payments for select using (current_user_has_permission('suppliers.view') or current_user_is_manager());
create policy employees_view on public.employees for select using (current_user_has_permission('employees.view') or current_user_is_manager());
create policy employees_create on public.employees for insert with check (current_user_has_permission('employees.create') and created_by=auth.uid());
create policy employees_update on public.employees for update using (current_user_has_permission('employees.edit') or current_user_is_manager()) with check (current_user_has_permission('employees.edit') or current_user_is_manager());
create policy employee_advances_view on public.employee_advances for select using (current_user_has_permission('payroll.view') or current_user_is_manager());
create policy employee_incentives_view on public.employee_incentives for select using (current_user_has_permission('payroll.view') or current_user_is_manager());
create policy payroll_periods_view on public.payroll_periods for select using (current_user_has_permission('payroll.view') or current_user_is_manager());
create policy payroll_records_view on public.payroll_records for select using (current_user_has_permission('payroll.view') or current_user_is_manager());
create policy roles_view on public.roles for select using (current_user_is_manager() or current_user_has_permission('users.view'));
create policy permissions_view on public.permissions for select using (current_user_is_manager() or current_user_has_permission('users.view'));
create policy role_permissions_view on public.role_permissions for select using (current_user_is_manager() or current_user_has_permission('users.view'));
create policy profiles_view on public.profiles for select using (id=auth.uid() or current_user_is_manager() or current_user_has_permission('users.view'));
create policy user_roles_view on public.user_roles for select using (user_id=auth.uid() or current_user_is_manager() or current_user_has_permission('users.view'));
create policy settings_view on public.settings for select using (current_user_is_manager());
create policy products_view on public.products for select using (current_user_has_permission('products.view') or current_user_is_manager());
create policy products_create on public.products for insert with check (current_user_has_permission('products.create') and created_by=auth.uid());
create policy products_update on public.products for update using (current_user_has_permission('products.edit') or current_user_is_manager()) with check (current_user_has_permission('products.edit') or current_user_is_manager());
create policy inventory_view on public.stock_movements for select using (current_user_has_permission('inventory.view') or current_user_is_manager());
create policy inventory_lines_view on public.stock_movement_lines for select using (current_user_has_permission('inventory.view') or current_user_is_manager());
create policy warehouse_view on public.warehouses for select using (current_user_has_permission('inventory.view') or current_user_is_manager());
create policy sales_view on public.sales for select using (current_user_has_permission('sales.view') or current_user_is_manager());
create policy sales_items_view on public.sale_items for select using (current_user_has_permission('sales.view') or current_user_is_manager());
create policy sales_payments_view on public.sale_payments for select using (current_user_has_permission('sales.view') or current_user_is_manager());
create policy suppliers_view on public.suppliers for select using (current_user_has_permission('suppliers.view') or current_user_is_manager());
create policy purchases_view on public.purchases for select using (current_user_has_permission('purchases.view') or current_user_is_manager());
create policy purchase_items_view on public.purchase_items for select using (current_user_has_permission('purchases.view') or current_user_is_manager());
create policy raw_materials_view on public.raw_materials for select using (current_user_has_permission('inventory.view') or current_user_has_permission('purchases.view') or current_user_is_manager());
create policy production_orders_view2 on public.production_orders for select using (current_user_has_permission('production.view') or current_user_is_manager());
create policy production_materials_view2 on public.production_materials for select using (current_user_has_permission('production.view') or current_user_is_manager());
create policy returns_view on public.returns for select using (current_user_has_permission('returns.view') or current_user_is_manager());
create policy return_items_view on public.return_items for select using (current_user_has_permission('returns.view') or current_user_is_manager());
create policy damaged_view on public.damaged_goods for select using (current_user_has_permission('returns.view') or current_user_has_permission('production.view') or current_user_is_manager());
create policy transfers_view on public.finance_transfers for select using (current_user_has_permission('treasury.view') or current_user_is_manager());
create policy counts_view on public.cash_counts for select using (current_user_has_permission('treasury.view') or current_user_is_manager());
create policy customers_view on public.customers for select using (current_user_has_permission('sales.view') or current_user_is_manager());
create policy departments_view on public.departments for select using (current_user_has_permission('employees.view') or current_user_is_manager());
create policy jobs_view on public.job_titles for select using (current_user_has_permission('employees.view') or current_user_is_manager());
create policy shifts_view on public.shifts for select using (current_user_has_permission('employees.view') or current_user_is_manager());
create policy categories_view on public.product_categories for select using (current_user_has_permission('products.view') or current_user_is_manager());
create policy units_view on public.units for select using (current_user_has_permission('products.view') or current_user_is_manager());
